### PR TITLE
gluon-quickfix: Only check one device, if there are more than one

### PR DESCRIPTION
**Pull request by rubo77**

### CODE REVIEW

**Comment by rubo77** [comment]
this would close #11

**Comment by rubo77** [comment]
Where is the file gone in your branches?

**Comment by ghost** [comment]
It's in branch into v2016.2

**Comment by rubo77** [comment]
it is not here:

https://github.com/eulenfunk/packages/tree/v2016.2.x
I see!

 the branch without .x :)

**Comment by ghost** [comment]
v2016.2: This branch is 15 commits ahead, 17 commits behind master.
v2016.2.x: This branch is 1 commit behind master.

it was never implemented in that branch v2016.2.x

**Comment by Adorfer** [comment]
lässt sich das irgendwie zusammenführen? Ist hier zwar off-topic evtl, aber ich bin wirklich nicht der Git-Experte.

**Pull request merged**
